# start window statics

MENU_WIDTH = 400
MENU_HEIGHT = 300
TEXT_MARGIN_WIDTH = 40
TEXT_MARGIN_HEIGHT = 10
BUTTON_MARGIN_WIDTH = 150
BUTTON_MARGIN_HEIGHT = 130
BUTTON_WIDTH = 20
BUTTON_HEIGHT = 2
TEXT_ENTRY_WIDTH = 20
BUTTON_BETWEEN_DISTANCE = 80

# board statics

HEX_ACCURACY = 0.87
SCREEN_OCCUPATION = 0.8
BOARD_OCCUPATION = 0.9
WIDTH_PROPORTION = 7
HEIGHT_PROPORTION = 20
DISABLED = 0
ENABLED = 1

TEXT_BOX_COLOR = "black"
FONT_SIZE = 16
BUTTON_COLOR = "lightgrey"
